name: tests

on:
  push:
    branches: [main]
  pull_request:
  # allows manual triggering of this workflow
  workflow_dispatch:

jobs:

  test:
    uses: ./.github/workflows/build.yml

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - name: Run all tests
        run: |
          ./tasks/test.sh
        env:
          PYTHONPATH: .
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
